DROP TABLE IF EXISTS planes CASCADE;

CREATE TABLE planes (
    pid INT auto_increment,
    name VARCHAR(255),
    dir VARCHAR(255),
    PRIMARY KEY(pid)
) ENGINE = innodb;

INSERT INTO planes (name, dir) VALUES
('chaotic aether', 'opca-1-chaotic-aether.jpg'),
('the aether flues', 'opca-10-the-aether-flues.jpg'),
('agyrem', 'opca-11-agyrem.jpg'),
('akoum', 'opca-12-akoum.jpg'),
('aretopolis', 'opca-13-aretopolis.jpg'),
('astral arena', 'opca-14-astral-arena.jpg'),
('bant', 'opca-15-bant.jpg'),
('bloodhill bastion', 'opca-16-bloodhill-bastion.jpg'),
('celestine reef', 'opca-17-celestine-reef.jpg'),
('cliffside market', 'opca-18-cliffside-market.jpg'),
('the dark barony', 'opca-19-the-dark-barony.jpg'),
('interplanar tunnel', 'opca-2-interplanar-tunnel.jpg'),
('edge of malacol', 'opca-20-edge-of-malacol.jpg'),
('eloren wilds', 'opca-21-eloren-wilds.jpg'),
('the eon fog', 'opca-22-the-eon-fog.jpg'),
('feeding grounds', 'opca-23-feeding-grounds.jpg'),
('fields of summer', 'opca-24-fields-of-summer.jpg'),
('the fourth sphere', 'opca-25-the-fourth-sphere.jpg'),
('furnace layer', 'opca-26-furnace-layer.jpg'),
('gavony', 'opca-27-gavony.jpg'),
('glen elendra', 'opca-28-glen-elendra.jpg'),
('glimmervoid basin', 'opca-29-glimmervoid-basin.jpg'),
('morphic tide', 'opca-3-morphic-tide.jpg'),
('goldmeadow', 'opca-30-goldmeadow.jpg'),
('grand ossuary', 'opca-31-grand-ossuary.jpg'),
('the great forest', 'opca-32-the-great-forest.jpg'),
('grixis', 'opca-33-grixis.jpg'),
('grove of the dreampods', 'opca-34-grove-of-the-dreampods.jpg'),
('hedron fields of agadeem', 'opca-35-hedron-fields-of-agadeem.jpg'),
('the hippodrome', 'opca-36-the-hippodrome.jpg'),
('horizon boughs', 'opca-37-horizon-boughs.jpg'),
('immersturm', 'opca-38-immersturm.jpg'),
('isle of vesuva', 'opca-39-isle-of-vesuva.jpg'),
('mutual epiphany', 'opca-4-mutual-epiphany.jpg'),
('izzet steam maze', 'opca-40-izzet-steam-maze.jpg'),
('jund', 'opca-41-jund.jpg'),
('kessig', 'opca-42-kessig.jpg'),
('kharasha foothills', 'opca-43-kharasha-foothills.jpg'),
('kilnspire district', 'opca-44-kilnspire-district.jpg'),
('krosa', 'opca-45-krosa.jpg'),
('lair of the ashen idol', 'opca-46-lair-of-the-ashen-idol.jpg'),
('lethe lake', 'opca-47-lethe-lake.jpg'),
('llanowar', 'opca-48-llanowar.jpg'),
('the maelstrom', 'opca-49-the-maelstrom.jpg'),
('planewide disaster', 'opca-5-planewide-disaster.jpg'),
('minamo', 'opca-50-minamo.jpg'),
('mirrored depths', 'opca-51-mirrored-depths.jpg'),
('mount keralia', 'opca-52-mount-keralia.jpg'),
('murasa', 'opca-53-murasa.jpg'),
('naar isle', 'opca-54-naar-isle.jpg'),
('naya', 'opca-55-naya.jpg'),
('nephalia', 'opca-56-nephalia.jpg'),
('norn s dominion', 'opca-57-norn-s-dominion.jpg'),
('onakke catacomb', 'opca-58-onakke-catacomb.jpg'),
('orochi colony', 'opca-59-orochi-colony.jpg'),
('reality shaping', 'opca-6-reality-shaping.jpg'),
('orzhova', 'opca-60-orzhova.jpg'),
('otaria', 'opca-61-otaria.jpg'),
('panopticon', 'opca-62-panopticon.jpg'),
('pools of becoming', 'opca-63-pools-of-becoming.jpg'),
('prahv', 'opca-64-prahv.jpg'),
('quicksilver sea', 'opca-65-quicksilver-sea.jpg'),
('raven s run', 'opca-66-raven-s-run.jpg'),
('sanctum of serra', 'opca-67-sanctum-of-serra.jpg'),
('sea of sand', 'opca-68-sea-of-sand.jpg'),
('selesnya loft gardens', 'opca-69-selesnya-loft-gardens.jpg'),
('spatial merging', 'opca-7-spatial-merging.jpg'),
('shiv', 'opca-70-shiv.jpg'),
('skybreen', 'opca-71-skybreen.jpg'),
('sokenzan', 'opca-72-sokenzan.jpg'),
('stairs to infinity', 'opca-73-stairs-to-infinity.jpg'),
('stensia', 'opca-74-stensia.jpg'),
('stronghold furnace', 'opca-75-stronghold-furnace.jpg'),
('takenuma', 'opca-76-takenuma.jpg'),
('talon gates', 'opca-77-talon-gates.jpg'),
('tazeem', 'opca-78-tazeem.jpg'),
('tember city', 'opca-79-tember-city.jpg'),
('time distortion', 'opca-8-time-distortion.jpg'),
('trail of the mage rings', 'opca-80-trail-of-the-mage-rings.jpg'),
('truga jungle', 'opca-81-truga-jungle.jpg'),
('turri island', 'opca-82-turri-island.jpg'),
('undercity reaches', 'opca-83-undercity-reaches.jpg'),
('velis vel', 'opca-84-velis-vel.jpg'),
('windriddle palaces', 'opca-85-windriddle-palaces.jpg'),
('the zephyr maze', 'opca-86-the-zephyr-maze.jpg'),
('academy at tolaria west', 'opca-9-academy-at-tolaria-west.jpg');